
const questionText = [    
            
    "Antara yang berikut, kerajaan yang manakah yang mengekalkan kelangsungan pemerintahan Kesultanan Melayu Melaka?",
    "Apakah kepentingan Alat Regalia kepada Kesultanan Melayu Melaka?",
    "Jadual berikut menunjukkan perkembangan nasionalisme yang berlaku di Eropah pada Abad ke-18. Pasangan manakah yang betul?",
    "Gambar menunjukkan tokoh nasinalisme di Malaysia. Apakah kaedah yang digunakan untuk menyebarkan idea nasionalisme",
    "Mengapakah Jepun ingin menguasai Singapura pada Perang Dunia Kedua?",
    "Selepas kekalahan Jepun di Tanah Melayum rundingan telah diadakan pada Ogos 1945. Apakah kesan daripada usaha tersebut?",
    "Selepas Perang Dunia Ke-2, berlaku perubahan pentadbiran British di Tanah Melayu. Mengapakah perubahan tersebut berlaku?",
    "Mengapakah tiada bantahan daripada rakyat tempatan berkenaan penyerahan Sabah kepada British?",
    "Perangkaan Perlembagaan Persekutuan Tanah Melayu yang baharu dilakukan untuk menggantikan Malayan Union. Siapakah Wakil X?",
    "Berdasarkan syarat kewarganegaraan mengikut Perjanjian Persekutuan Tanag Melayu 1948, apakah status kewarganegaraan individu tersebut?",
    "British telah meluluskan Trade Union Ordinance No.9 of 1948 di Tanah Melayu. Mengapakah undang-undang tersebut dilaksanakan?",
    "Kempen Bulan Rakyat Melawan Penjahat diadakan oleh penduduk tempatan pada tahun 1949 di Tanah Melayu. Apakah kesan kempen tersebut?",
    "Kenyataan manakah yang menepati dengan Penyata Jawatankuasa Pelajaran 1956?",
    "Apakah yang terkandung dalam Manifesto Perlembagaan Rakyat, hasil daripada pakatan antara PUTERA dan AMCJA?",
    "Mengapakah Parti Perikatan mencapai kemenangan besar ketika Pilihan Raya Majlis Perundangan Persekutuan 1955?",
    "Apakah peranan Majlis Perundangan Persekutuan 1955 di Tanah Melayu?",
    "Apakah sumbangan tokoh abad ke-20, ulama Syeikh Abdul Fahim?",
    "Berikut adalah reaksi terhadap draf Perlembagaan Persekutuan Tanah Melayu. Apakah X?",
    "Pada 25 Januari 1961, Pelancaran Rancangan Buku Merah adalah salah satu usaha untuk membangunkan negara selepas kemerdekaan. Apakah matlamat rancangan itu?",
    "Jata negara telah diperkenalkan oleh Raja-raja Melayu pada tahun 1957. Apakah maksud lima bilah keris dalam Jata Negara?",
    "Deklarasi Persahabatan PBB telah diperkenalkan pada tahun 1970. Apakah kepentingan deklarasi tersebut?",
    "Dalam mempertahankan kedaultan negara, apakah peranan rakyat?",
    "Sebelum kedatangan British, Hukum Kanun Pahang dan Undang-Undang 99 Perak merupakan antara undang-undang yang digubal di Negeri Melayu. Apakah persamaan kedua-dua undang-undang tersebut?",
    "Sebelum kemerdekaan, Majlis Negeri, Majlis Persekutuan dan Majlis Perundangan Negeri dibentuk sebagai X. Apakah X?",
    "Apakah kesan penubuhan Durbar Negeri-negeri Melayu Bersekutu (NNMB) pada tahun 1897?",
    "Antara yang berikut, situasi manakah yang membolehkan Yang di-Pertuan Agong mngisytiharkan darurat di negara kita?",
    "Pada tahun 2005, Rancangan Pembangunan Koridor Wilayah telah dilaksanakan. Apakah tujuan rancangan ini?",
    "Pernyataan berikut adalah emngenai Perkara 75 Perlembagaan Persekutuan. Yang manakah merupakan kepentingan perkara tersebut?",
    "Mengapa Parti Rakyat Brunei pimpinan A. M. Azahari menentang cadangan Pembentukan Malaysia pada tahun 1963?",
    "Pada tahun 1963, berlaku konfrontasi Indonesia terhadap pembentukan Malaysia. Bagaimanakah Malaysia menangani perkara tersebut?",
    "Apakah persamaan antara kedua-dua usaha kerajaan dalam menentang komunis yang dinyatakan?",
    "Apakah faktor yang mencetuskan Peristiwa 13 Mei?",
    "Pada tahun 1992, intitusi tersebut telah ditubuhkan. Apakah tugas institusi tersebut?",
    "Prinsip kelima Rukun Negara ialah Kesopanan dan Kesusilaan. Mengapakah warganegara Malaysia perlu menghayati prinsip tersebut?",
    "Majlis Perundingan Negara (MAPEN) ditubuhkan pada Jan 1970. Apakah tujuan penubuhan majlis tersebut?",
    "Dasar Pembangunan Nasional (DPN) bertujuan menyatukan rakyat melalui pengagihan kekayaan yang adil. Bagaimanakah hasrat tersebut dapat dicapai?",
    "Pada April 1971, Perjanjian Pertahanan LIMA negara (FDPA) telah ditandatangani. Apakah bantuan yang diterima oleh Malaysia ?",
    "Mengapakah Malaysia menandatangani Perisytihan Lusaka pada 1970?",
    "Malaysia memulihkan krisis kewangan negara pada tahun 1970-1998 dengan cara ...",
    "Bagaimanakah isu pelarian Rohingya ke negara kita ditangani?"
]

const options = [   
    ["Johor-Riau", "Champa", "Srivijaya", "Majapahit"],
    ["Lambang Kemakmuran", "Simbol Kekayaan", "Simbol Kedaulatan", "Lambang Persahabatan"],
    ["Pentadbiran Birokrasi & Amalan sistem Demokrasi", "Hak rakyat membentuk Kerajaan & Pengukuhan kuasa Raja", "Parlimen menggubal undang-undang & Raja menentukan undang-undang", "Raja Berpelambagaan diperkenalkan & Pelaksanaan sistem republik"],
    ["Menerbitkan Akhbar", "Menulis Karya Kreatif", "Membentuk parti politik", "Membangunkan madrasah"],
    ["Membentuk Persekutuan Borneo", "Menyekat kemaraan Tentera Bersekutu", "Meningkatkan Perdagangan di Selat Melaka", "Memudahkan penguasaan minyak di Sumatera"],
    ["Mengembalikan keamanan", "Mengeratkan hubungan antara kaum", "Mengiktiraf kewibawaan pemimpin Melayu", "Mengukuhkan kerjasama dalam pentadbiran"],
    ["Desakan golong radikal", "Ketegasan pemimpin Melayu", "Pelaksanaan sistem demokrasi", "Pembentukan Jawatankuasa Eksekutif"],
    ["Kegiatan persatuan ditindas", "Kerjasama baik antara kaum", "Masalah kewangan meruncing", "Pentadbiran negeri diserahkan kepada pemimpin tempatan"],
    ["Rakyat Tempatan", "Pembesar negeri", "Raja-raja Melayu", "Pemimpin parti radikal"],
    ["Rakyat British", "Rakyat Dagang", "Raja-raja Melayu", "Rakyat Malayan Union"],
    ["Menghalang pengaruh parti radikal", "Mengekang pengaruh komunis", "Menyekat kebebasan bersuara", "Mengawal penerbitan risalah"],
    ["Pengukuhan kerjasama pelbagai kaum", "Pertambahan bilangan imigran", "Peningkatan kesedaran berpolitik", "Pemerkasaan perkhidmatan awam"],
    ["I dan II", "I dan IV", "II dan III", "III dan IV"],
    
    ["Pelaksanaan pilihanraya", "Pemerintahan bercorak politik", "Pembentukan Dewan Perundangan", "Penganjuran Persidangan Kebangsaan"],
    ["Mendaftarkan calon lebih awal", "Meletakkan calon berpendidikan", "Memperjuangkan hak sama rata", "Mengadakan kerjasama politik"],
    ["Membubarkan parlimen", "Menggubal undang-undang", "Melantik Ahli Jemaah Menteri", "Membentuk Jawatankuasa Pilihanraya"],
    ["Memperjuangkan kebebasan bersuara", "Menetapkan tarikh kemerdekaan", "Menyertai rombongan ke London", "Mengasaskan pasukan Tentera Selempang Merah"],
    ["Melindungi kedudukan Raja-raja Melayu", "Memperakui Islam sebagai agama rasmi", "Menolak syarat kewarganegaraan yang longgar", "Menjadikan Bahasa Mandarin sebagai bahasa kebangsaan"],
    ["Menambah pengeluaran bahan makanan", "Mengoptimumkan penggunaan tanah", "Menyediakan peluang pekerjaan", "Memantau projek pembangunan"],
    ["Negeri-negeri Selat", "Islam agama rasmi", "Warisan ketamadunan Melayu", "Negara Melayu Tidak Bersekutu"],
    ["Menekankan prinsip persamaan kedaulatan", "Mewujudkan pakatan ketenteraan", "Menghapuskan amalan kuasa veto", "Menamatkan persaingan senjata nuklear"],
    ["I dan II", "I dan IV", "II dan III", "III dan IV"],
    ["I dan II", "I dan IV", "II dan III", "III dan IV"],
    ["Menggubal undang-undang", "Membentuk dasar pentadbiran", "Menjadi Penasihat kepada sultan", "Kuasa persekutuan dan negeri diagihkan"],
    ["Sultan hilang kuasa", "Majlis Raja-raja ditubuhkan", "Gabenor Mengetuai pentadbiran", "Perebutan kuasa antara pemimpin"],
    ["Perebutan kuasa antara pemimpin", "Peningkatan kos sara hidup", "Pertikaian sempadan negeri", "Perbalahan antara kaum"],
    ["Mengawal keselamatan sempadan", "Menggalakkan kemasukan buruh asing", "Mengadakan kerjasama luar negara", "Mewujudkan keseimbangan pembangunan negeri"],
    ["Mengukuhkan sistem persekutuan", "Mengagihkan kuasa secara saksama", "Mengawal perkhidmatan awam negeri", "Menentukan kuasa Kerajaan Tempatan"],    
    ["Menubuhkan kesatuan wilayah Borneo", "Melambatkan proses kemerdekaan", "Membendung ancaman komunis", "Mengawal kestabilan politik Asia Tenggara"],
    ["I dan II", "I dan IV", "II dan III", "III dan IV"],
    ["Pusat pembangunan teknologi", "Pusat penyelidikan ilmu", "Pusat ko kurikulum", "Pusat kegiatan guru"],
    ["Melancarkan perang gerila", "Menawarkan pengampunan", "Membina penempatan baharu", "Membentuk pasukan sukarelawan"],
    ["Pelaksanaan cukai tinggi", "Kemasukan pendatang asing", "keputusan pilihanraya umum", "Provokasi daripada negara luar"],
    ["Meningkatkan taraf hidup rakyat", "Melahirkan masyarakat bertoleransi", "Mewujudkan masyarakat berdaya saing", "Mengekalkan persamaan hak"],
    ["Meningkatkan taraf pendidikan", "Memperkukuhkan dasar luar negara", "Mewujudkan masyarakat demokratik", "Memupuk integrasi nasional"],
    ["Melaksanakan skim gaji minimum", "Menimbangi pembangunan antara negeri", "Memperkenalkan ekonomi kawalan", "Mewajibkan pemilikan saham"],
    ["I dan II", "I dan IV", "II dan III", "III dan IV"],
    ["Mendesak pengharaman senjata nuklear", "Memerangi perdagangan manusia", "Menangani isu perebutan wilayah", "Mengatasi pelanunan"],
    ["Membuat pinjaman luar", "Menggunakan mata wang dinar", "Menambat kadar penukaran mata wang", "MEnambah bilangan institusi kewangan"],
    ["Menambah kem pelarian", "meningkatkan kerjasama serantau", "Membuat bantahan di Mahkamah Antarabangsa", "Memutuskan hubungan diplomatik dengan Myanmar"],

]
const answerList = [
"A", "C", "D", "B", "D", "A", "B", "A", "C", "A",
"B", "A", "B", "C", "D", "B", "B", "C", "D", "D",
"A", "C", "D", "A", "B", "D", "D", "A", "A", "B",
"C", "C", "B", "B", "D", "B", "D", "A", "C", "B"
]